spring:
  application:
    name: t-and-t

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
